#!/bin/bash

macos_url="https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-macos.tar.gz"
linux_url="https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz"

if [ `uname` == "Linux" ]; then
  url="$linux_url"
fi

if [ `uname` == "Darwin" ]; then
  url="$macos_url"
fi

if [ -z "$url" ]; then
  echo "unknown OS, exit"
  exit 1
fi

if [ ! -s test-libs ]; then
  mkdir test-libs
fi

if [ ! -f test-libs/geckodriver ]; then
  cd test-libs || exit 1
  curl --location -o geckodriver.tar.gz "$url"
  tar xvf geckodriver.tar.gz
  cd ..
fi

